version: '3.8'

services:
  web:
    build: .
    image: coe-dynamic-hosting:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_PATH=/app/data/cloud_storage.db
      - UPLOAD_FOLDER=/app/uploads
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
    volumes:
      # Persistent storage for database and uploads
      - app_data:/app/data
      - app_uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/', timeout=5)"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          # AWS Free Tier friendly limits
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

volumes:
  app_data:
  app_uploads:
