apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # This is a base64 encoded secret key - replace with your own
  # To generate: echo -n "your-secret-key-here" | base64
  secret-key: eW91ci1zZWNyZXQta2V5LWhlcmU=
