apiVersion: v1
kind: Service
metadata:
  name: coe-dynamic-hosting-service
  labels:
    app: coe-dynamic-hosting
spec:
  selector:
    app: coe-dynamic-hosting
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
